# -*- coding: utf-8 -*-
"""yolov8_training_4_14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zdOoiifpuVDqZvVZS0ErL5t8faSkqGuv
"""

!nvidia-smi

!pip install ultralytics==8.0.196

from ultralytics import YOLO
import os
from IPython.display import display, Image
from IPython import display
display.clear_output()

!yolo task=detect mode=predict model=yolov8n.pt conf=0.25 source=/content/street.jpeg

Image(filename='/content/runs/detect/predict/street.jpeg')

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="I3MGvg0ASMxpqXabEqml")
project = rf.workspace("sc-robotics").project("mallet-0ga9i")
version = project.version(8)
dataset = version.download("yolov8")

!yolo task=detect mode=train model=yolov8m.pt data={dataset.location}/data.yaml epochs=150 imgsz=640